### ISSUE TITLE
try to get website speed, but i can read only ''domain.com'' i can't read files like css , js why?

### ISSUE THREAD

**Issue by ghost** [technopagan/simple-website-speed-test#1]
Hello,
I try to get website speed of some website, but i can read only ''domain.com'' i can't read website files like css , js ... why ? i use proxies for this job.

here is the php code:

$options = array(
                'useragent'      => "Firefox (+http://www.firefox.org)", // who am i
                'connecttimeout' => 120, // timeout on connect
                'timeout'          => 120, // timeout on response
                'redirect'          => 10, // stop after 10 redirects
                'referer'           => "http://www.google.com",
                'proxyhost'        =>'85.25.8.14:80'
        );
$response = http_get("http://solve-ict.com/wp-content/themes/ict%20theme/js/jquery-1.7.1.min.js", $options , $info);
but it works fine with http://domain.com/ , but with files css or js it gives 404, using some free proxy servers available

?

Thanks.

**Comment by technopagan** [comment]
That's because this tool uses Phantomas (https://github.com/macbre/phantomas) under the hood which already takes an entire website with all its CSS, JS etc. into account. It doesn't work if you point it at URLs for single assets such as CSS or JS.
